[project]
name = "uci-secom-outlier-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Samuel Padron", email = "spadron05@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "pytest>=9.1.1",
    "scikit-learn>=1.9.0",
]

[project.scripts]
uci-secom-outlier-detection = "uci_secom_outlier_detection:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
