# UCI-SECOM Dataset EDA

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from uci_secom_outlier_detection.data_loader import load_dataset

In [144]:
df, y = load_dataset()
stats_df = df.describe()

In [ ]:
print(df.head())
print(df.shape)
print(stats_df)

In [18]:
print(y.head(3))
y.shape

0   -1
1   -1
2    1
Name: label, dtype: int64


(1567,)

In [145]:
missing_pct = df.isna().mean().sort_values(ascending=False)
print(missing_pct.head(10))
print((missing_pct > 0.20).sum()) # how many have >20% missing values
variances = df.var()
print((variances < 1e-6).sum()) # how many columns are almost constant

feature_292    0.911934
feature_293    0.911934
feature_158    0.911934
feature_157    0.911934
feature_492    0.855775
feature_85     0.855775
feature_358    0.855775
feature_220    0.855775
feature_244    0.649649
feature_517    0.649649
dtype: float64
32
127


There seems to be some subgroups of features that have the same exact percentage. This is unlikely to be due to chance, and might be indicating a shared a common mode of failure.

In [141]:
fail_rate = (y == 1).mean()
print(f"{fail_rate:.2%} ({(y == 1).sum()} fails out of {len(y)})")

6.64% (104 fails out of 1567)


104 failts out of 1567 matches the dataset description.

In [142]:
print(df.shape)

(1567, 590)


In [143]:
print(variances[variances < 1e-6])
print(variances[variances < 1e-6].shape)
df.drop(variances[variances < 1e-6].index, axis=1, inplace=True, errors='ignore')

feature_5      0.000000e+00
feature_13     0.000000e+00
feature_42     0.000000e+00
feature_49     0.000000e+00
feature_52     0.000000e+00
                   ...     
feature_535    0.000000e+00
feature_536    0.000000e+00
feature_537    0.000000e+00
feature_538    0.000000e+00
feature_544    8.733216e-08
Length: 127, dtype: float64
(127,)
